spring:
  application:
    name: stepapp

  datasource:
    url: ${DATABASE_URL}
#    url: jdbc:postgresql://localhost:5432/stepapp
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8080


security:
  jwt:
    secret: "c608517eaa35c687d35746a3f8d5b555"
    expiration-ms: 3600000
